fips-mode-setup: Use grub2-editenv to modify the kernelopts for BLS
With grubby being the BLS wrapper the kernel options will not apply
to updated kernels.
The grub2-editenv command needs to be called to modify kernelopts
in /boot/grub2/grubenv.

diff --git a/fips-mode-setup b/fips-mode-setup
--- a/fips-mode-setup
+++ b/fips-mode-setup
@@ -93,14 +93,27 @@ fi
 
 echo "FIPS mode will be $(enable2txt $enable_fips)."
 
+fipsopts="fips=$enable_fips boot=UUID=$boot_device_uuid"
+
 if test $boot_config = 0 ; then
-	echo "Now you need to configure the bootloader to add kernel options \"fips=$enable_fips boot=UUID=$boot_device_uuid\""
+	echo "Now you need to configure the bootloader to add kernel options \"$fipsopts\""
 	echo "and reboot the system for the setting to take effect."
 else
 	default_kernel="$(grubby --default-kernel)"
-	grubby --update-kernel=$default_kernel --args="fips=$enable_fips boot=UUID=$boot_device_uuid"
+	grubby --update-kernel=$default_kernel --args="$fipsopts"
 	if test x"$(uname -m)" = xs390x ; then
 		zipl >/dev/null 2>&1
+	else
+		if test ! -x "$(command -v grub2-editenv)" ; then
+			echo "The grub2-editenv command is missing, please check your bootloader configuration."
+		else
+			kernelopts=$(grub2-editenv list | grep kernelopts | sed 's/^kernelopts=//;s/fips=[^ ]*//;s/boot=[^ ]*//')
+			if test -z "$kernelopts" ; then
+				echo "No kernelopts in grub2 environment, please check your bootloader configuration."
+			else
+				grub2-editenv - set kernelopts="$kernelopts $fipsopts" || echo "The grub2-editenv command failed, please check your bootloader configuration."
+			fi
+		fi
 	fi
 	echo "Please reboot the system for the setting to take effect."
 fi
