Generate java crypto policies

diff --git a/update-crypto-policies b/update-crypto-policies
--- a/update-crypto-policies
+++ b/update-crypto-policies
@@ -32,6 +32,7 @@ gnutls_config_file=$backend_config_dir/gnutls.config
 openssl_config_file=$backend_config_dir/openssl.config
 nss_config_file=$backend_config_dir/nss.config
 bind_config_file=$backend_config_dir/bind.config
+java_config_file=$backend_config_dir/java.config
 
 profile=$(cat $base_dir/config|grep -v ^#)
 
@@ -118,6 +119,13 @@ if ! test -f $bind_config_file.tmp;then
 fi
 echo -e "$CONFIG_BIND" > $bind_config_file.tmp 2>&1
 
+touch $java_config_file.tmp >/dev/null 2>&1
+if ! test -f $java_config_file.tmp;then
+	echo "Cannot write to $backend_config_dir. This program requires administrator permissions."
+	exit 1
+fi
+echo -e "$CONFIG_JAVA" > $java_config_file.tmp 2>&1
+
 # Test policies
 if test nocheck = 0 && test -x /usr/sbin/named-checkconf;then
 	/usr/sbin/named-checkconf >/dev/null 2>&1
@@ -134,6 +142,7 @@ if test $errcode = 0;then
 	mv $openssl_config_file.tmp $openssl_config_file
 	mv $gnutls_config_file.tmp $gnutls_config_file
 	mv $bind_config_file.tmp $bind_config_file
+	mv $java_config_file.tmp $java_config_file
 fi
 
 if test -e /usr/lib/systemd/system/bind.service;then
