better output and error code check.

diff --git a/update-crypto-policies b/update-crypto-policies
--- a/update-crypto-policies
+++ b/update-crypto-policies
@@ -1,11 +1,13 @@
 #!/bin/sh
 
+umask 022
+
 config_dir=/usr/lib/crypto-profiles/profiles
 base_dir=/etc/crypto-profiles
 backend_config_dir=$base_dir/back-ends
 errcode=0
 
-mkdir -p $backend_config_dir
+mkdir -p $backend_config_dir >/dev/null 2>&1
 
 gnutls_config_file=$backend_config_dir/gnutls.config
 openssl_config_file=$backend_config_dir/openssl.config
@@ -32,22 +34,23 @@ fi
 # preferred, but for compatibility reasons, the TLS RSA is prioritized
 # over DHE-RSA.
 
-if ! test -f $config_dir/$profile;then
+if ! test -f $config_dir/$profile.settings;then
 	echo "Unknown profile: $profile"
 	exit 1
 fi
 
-. $config_dir/$profile
+. $config_dir/$profile.settings
 
 # Generate policy for GnuTLS
-echo $CONFIG_GNUTLS > $gnutls_config_file.tmp
+touch $gnutls_config_file.tmp >/dev/null 2>&1
 if ! test -f $gnutls_config_file.tmp;then
-	echo "Cannot write to $backend_config_dir"
+	echo "Cannot write to $backend_config_dir. This program requires administrator permissions."
 	exit 1
 fi
+echo $CONFIG_GNUTLS > $gnutls_config_file.tmp
 
 # Test policies
-gnutls-cli -l --priority `cat $gnutls_config_file.tmp` >/dev/null
+gnutls-cli -l --priority `cat $gnutls_config_file.tmp|sed 's/SYSTEM=//g'` >/dev/null 2>&1
 if test $? != 0;then
 	echo "Couldn't update policy for GnuTLS"
 	echo "There is an error in $gnutls_config_file"
@@ -58,14 +61,15 @@ fi
 
 
 # Generate policy for openssl
-echo $CONFIG_OPENSSL > $openssl_config_file.tmp
+touch $openssl_config_file.tmp >/dev/null 2>&1
 if ! test -f $openssl_config_file.tmp;then
-	echo "Cannot write to $backend_config_dir"
+	echo "Cannot write to $backend_config_dir. This program requires administrator permissions."
 	exit 1
 fi
+echo $CONFIG_OPENSSL > $openssl_config_file.tmp 2>&1
 
 # Test policies
-openssl ciphers `cat $openssl_config_file.tmp` >/dev/null
+openssl ciphers `cat $openssl_config_file.tmp` >/dev/null 2>&1
 if test $? != 0;then
 	echo "Couldn't update policy for OpenSSL"
 	echo "There is an error in $openssl_config_file.tmp"
