generate configure for bind

diff --git a/update-crypto-policies b/update-crypto-policies
--- a/update-crypto-policies
+++ b/update-crypto-policies
@@ -31,6 +31,7 @@ mkdir -p $backend_config_dir >/dev/null 2>&1
 gnutls_config_file=$backend_config_dir/gnutls.config
 openssl_config_file=$backend_config_dir/openssl.config
 nss_config_file=$backend_config_dir/nss.config
+bind_config_file=$backend_config_dir/bind.config
 
 profile=`cat $base_dir/config|grep -v ^#`
 
@@ -66,7 +67,7 @@ if ! test -f $gnutls_config_file.tmp;then
 	echo "Cannot write to $backend_config_dir. This program requires administrator permissions."
 	exit 1
 fi
-echo $CONFIG_GNUTLS > $gnutls_config_file.tmp
+echo -e $CONFIG_GNUTLS > $gnutls_config_file.tmp
 
 # Test policies
 if test nocheck = 0 && test -x /usr/bin/gnutls-cli;then
@@ -84,7 +85,15 @@ if ! test -f $openssl_config_file.tmp;then
 	echo "Cannot write to $backend_config_dir. This program requires administrator permissions."
 	exit 1
 fi
-echo $CONFIG_OPENSSL > $openssl_config_file.tmp 2>&1
+echo -e $CONFIG_OPENSSL > $openssl_config_file.tmp 2>&1
+
+# Generate policy for bind
+touch $bind_config_file.tmp >/dev/null 2>&1
+if ! test -f $bind_config_file.tmp;then
+	echo "Cannot write to $backend_config_dir. This program requires administrator permissions."
+	exit 1
+fi
+echo -e $CONFIG_BIND > $bind_config_file.tmp 2>&1
 
 # Test policies
 if test nocheck = 0 && test -x /usr/bin/openssl;then
@@ -100,6 +109,11 @@ fi
 if test $errcode = 0;then
 	mv $openssl_config_file.tmp $openssl_config_file
 	mv $gnutls_config_file.tmp $gnutls_config_file
+	mv $bind_config_file.tmp $bind_config_file
+fi
+
+if test -e /usr/lib/systemd/system/bind.service;then
+	systemctl reload bind
 fi
 
 # Old versions seemed to install that file. We no longer use it
